version: '3'

services:
  r-service:
    build:
      context: .
      dockerfile: Dockerfile-R
    volumes:
      - ./data:/app/data

  api:
    build:
      context: .
      dockerfile: Dockerfile-Python
    ports:
      - "8081:8081"
    volumes:
      - ./data:/app/data
    depends_on:
      - r-service